/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Model.BadConsequenceNumTreasures;
/**
 *
 * @author sagrario
 */
public class BadConsequenceNumTreasuresView extends javax.swing.JPanel {
    private BadConsequenceNumTreasures bcNumModel;
    /**
     * Creates new form BadConsequenceNumTreasuresView
     */
    public BadConsequenceNumTreasuresView() {
        initComponents();
    }

    public void setBadConsequenceNumTreasuresModel(BadConsequenceNumTreasures bc){
        bcNumModel = bc;
        
        text.setText(bcNumModel.getText());
        levels.setText(Integer.toString(bcNumModel.getLevels()));
        numVisibles.setText(Integer.toString(bcNumModel.getnVisibleTreasures()));
        numHidden.setText(Integer.toString(bcNumModel.getnHiddenTreasures()));
        
        
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        numVisibles = new javax.swing.JLabel();
        numHidden = new javax.swing.JLabel();

        levels.setText("Niveles que pierdes:");

        numVisibles.setText("Numero de tesoros visibles que pierdes:");

        numHidden.setText("Numero de tesoros ocultos que pierdes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numVisibles)
                            .addComponent(levels)
                            .addComponent(numHidden))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(levels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numVisibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numHidden)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levels;
    private javax.swing.JLabel numHidden;
    private javax.swing.JLabel numVisibles;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
