/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Model.Monster;

/**
 *
 * @author usuario
 */
public class MonsterView extends javax.swing.JFrame {
    
    private Monster monsterModel;

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        levelAgainstCultist = new javax.swing.JLabel();
        prizeView = new GUI.PrizeView();
        bcDeathView = new GUI.BadConsequenceDeathView();
        bcNumTreasuresView = new GUI.BadConsequenceNumTreasuresView();
        bcTypeTreasureView = new GUI.BadConsequenceTypeTreasureView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("NAME");

        combatLevel.setText("Level");

        levelAgainstCultist.setText("Level against cultist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(combatLevel)
                            .addComponent(levelAgainstCultist))
                        .addGap(42, 42, 42)
                        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bcDeathView, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bcNumTreasuresView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bcTypeTreasureView, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(name)
                        .addGap(18, 18, 18)
                        .addComponent(combatLevel)
                        .addGap(18, 18, 18)
                        .addComponent(levelAgainstCultist))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcNumTreasuresView, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcTypeTreasureView, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcDeathView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMonster(Monster m){
        monsterModel = m;
        
        name.setText(monsterModel.getName().toUpperCase());
        combatLevel.setText("Nivel: " + Integer.toString(monsterModel.getCombatLevel()));
        levelAgainstCultist.setText("Nivel contra sectario: " + Integer.toString(monsterModel.getLevelChangeAgainstCultistPlayer()));
        
        
        bcNumTreasuresView.setBadConsequenceNumTreasuresModel(monsterModel.getBadConsequence());
        bcTypeTreasureView.setBadConsequenceTypeTreasuresModel(monsterModel.getBadConsequence());
        bcDeathView.setBadConsequenceDeathModel(monsterModel.getBadConsequence());
        prizeView.setPrize(monsterModel.getPrize());
        
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceDeathView bcDeathView;
    private GUI.BadConsequenceNumTreasuresView bcNumTreasuresView;
    private GUI.BadConsequenceTypeTreasureView bcTypeTreasureView;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel levelAgainstCultist;
    private javax.swing.JLabel name;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
